apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  namespace: monitoring
  labels:
    app: api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "{{DOCKER_IMAGE}}"
        ports:
        - containerPort: 5003
        env:
        - name: RDS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: dbuser
              key: RDS_USERNAME
        - name: RDS_HOST
          valueFrom:
            configMapKeyRef:
              name: dbhost
              key: RDS_HOST
        - name: RDS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: dbname
              key: RDS_DB_NAME
        - name: DB_SCHEMA_NAME
          valueFrom:
            configMapKeyRef:
              name: dbschema
              key: DB_SCHEMA_NAME
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: dbport
              key: RDS_PORT
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbpassword
              key: RDS_PASSWORD
